---
title: "Seinfeld Analysis"
output: html_notebook
author: "Chris Gargano"
---

```{r}
# Install packages
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
# Read in data file
data <- read.csv("../outputData/seinfeld.csv")

# Replace na values with 0
data[is.na(data)] <- 0

# View data
glimpse(data)
head(data)

# Re-order dataframe and drop non-numerical variables
data <- data[,c("IMDBrating", "Viewers",
                "PosTotal", "NegTotal", "CompTotal", "LineCountTotal", "WordCountTotal",
                "PosJerry", "NegJerry", "CompJerry", "LineCountJerry", "WordCountJerry",
                "PosGeorge", "NegGeorge", "CompGeorge", "LineCountGeorge", "WordCountGeorge",
                "PosKramer", "NegKramer", "CompKramer", "LineCountKramer", "WordCountKramer",
                "PosSecond", "NegSecond", "CompSecond", "LineCountSecond", "WordCountSecond",
                "PosOther", "NegOther", "CompOther", "LineCountOther", "WordCountOther",
                "Pilot", "Finale"
                )]
#summary(data)
```

```{r}
# Exploratory Data Analysis

# 1) Correlation Matrix
install.packages("corrplot")
library(corrplot)

corr_matrix <- corrplot.mixed(cor(data), lower = "shade", upper = "number",
                              number.cex = 0.4, tl.pos = "lt", tl.cex = 0.5,
                              tl.col = "black", tl.srt = 45, cl.cex = 0.5, cl.ratio = 0.1)

```

```{r}
# Exploratory Data Analysis

# 2) Plotting IMDBrating vs. _____

# IMDBrating vs. CompTotal (i.e. Total Compound Sentiment of an episode)
plot(data$IMDBrating, data$CompTotal, col = "black", lwd = 2,
     xlab = "IMDB Rating", ylab = "Compound Sentiment")

```


```{r}
# Begin Machine Learning

# Split data into test and training subsets

## 75% of the sample size
smp_size <- floor(0.75 * nrow(data))

## set the seed to make your partition reproductible
set.seed(42)
train_ind <- sample(seq_len(nrow(data)), size = smp_size)

train <- data[train_ind, ]
test <- data[-train_ind, ]
```

```{r}
# ML 1: Simple Linear Regression
# IMDBrating ~ .

fit1 <- lm(IMDBrating ~ ., train)
summary(fit1)

# Residual Plot
plot(fit1$residuals, type = "p", col = "red", lwd = 2,
     xlab = "Episode #", ylab = "Residual", main = "Residual Plot")

# Plot Actual vs. Predicted Values
plot(x = train$IMDBrating, y = fit1$fitted.values, type = "p", 
     xlab = "Actual IMDB Rating", ylab = "Predicted IMDB Rating",
     main = "Regression: Actuals vs. Predictions",
    xlim = c(7.5, 9.5), ylim = c(7.5, 9.5))

# Can't run the following code in a notebook...
# Need to run in the console window

# Plot actual IMDB Ratings in black
plot(train$IMDBrating, type = "l", col = "black", lwd = 2,
     ylim = c(-1, 10), xlab = "Episode #", ylab = "IMDB Rating",
     main = "Training Data: Actual vs. Predicted IMDB Ratings", 
     sub = "Black = Actual, Blue = Predicted, Green = Actual Average, Red = Model Resids, Gold = Predicted - Avg")
abline(0,0)

# Plot Actual Rating average in Green4
train_avg = rep(mean(train$IMDBrating), length(train$IMDBrating))
lines(train_avg, type = "l", col = "green4", lwd = 2)

# Plot fitted values in blue
lines(fit1$fitted.values, type = "l", col = "blue", lwd = 3)

# Plot residuals in red as bars
lines(fit1$residuals, type = "h", col = "red", lwd = 3)

# Plot Predicted - Average as gold dots
lines(fit1$fitted.values - train_avg, type = "p", col = "gold3")


### Examine fitted model vs. test data
pred1 <- predict(fit1, test)

# Plot actual IMDB Ratings in black
plot(test$IMDBrating, type = "l", col = "black", lwd = 2,
     ylim = c(-1, 10), xlab = "Episode #", ylab = "IMDB Rating",
     main = "Test Data: Actual vs. Predicted IMDB Ratings", 
     sub = "Black = Actual, Blue = Predicted, Green = Actual Average, Red = Model Resids, Gold = Predicted - Avg")
abline(0,0)

# Plot Actual Rating average in Green4
test_avg = rep(mean(test$IMDBrating), length(test$IMDBrating))
lines(test_avg, type = "l", col = "green4", lwd = 2)

# Plot fitted values in blue
lines(pred1, type = "l", col = "blue", lwd = 3)

# Plot residuals in red as bars
lines(test$IMDBrating - pred1, type = "h", col = "red", lwd = 3)

# Plot Predicted - Average as gold dots
lines(pred1 - test_avg, type = "p", col = "gold3")

```

```{r}
# ML 2: Random Forest, using randomForest library
library(randomForest)
#install.packages("reprtree")
#library(reprtree)

rf1 <- randomForest(IMDBrating ~ ., train)
summary(rf1)
rf1

names(rf1)

residuals <- data$IMDBrating - rf1$predicted

plot(train$IMDBrating, rf1$predicted)

# Plot Actual vs. Predicted Values
plot(x = train$IMDBrating, y = rf1$predicted, type = "p", 
     xlab = "Actual IMDB Rating", ylab = "Predicted IMDB Rating",
     main = "Random Forest: Actuals vs. Predictions",
    xlim = c(7.5, 9.5), ylim = c(7.5, 9.5))

# Can't run the following code in a notebook...
# Need to run in the console window

# Plot actual IMDB Ratings in black
plot(train$IMDBrating, type = "l", col = "black", lwd = 2,
     ylim = c(-1, 10), xlab = "Episode #", ylab = "IMDB Rating",
     main = "Training Data: Actual vs. Predicted IMDB Ratings", 
     sub = "Black = Actual, Blue = Predicted, Green = Actual Average, Red = Model Resids, Gold = Predicted - Avg")
abline(0,0)

# Plot Actual Rating average in Green4
train_avg = rep(mean(train$IMDBrating), length(train$IMDBrating))
lines(train_avg, type = "l", col = "green4", lwd = 2)

# Plot fitted values in blue
lines(rf1$predicted, type = "l", col = "blue", lwd = 3)

# Plot residuals in red as bars
lines(train$IMDBrating - rf1$predicted, type = "h", col = "red", lwd = 3)

# Plot Predicted - Average as gold dots
lines(rf1$predicted - train_avg, type = "p", col = "gold3")


### Examine fitted model vs. test data
pred_rf <- predict(rf1, test)

# Plot actual IMDB Ratings in black
plot(test$IMDBrating, type = "l", col = "black", lwd = 2,
     ylim = c(-1, 10), xlab = "Episode #", ylab = "IMDB Rating",
     main = "Test Data: Actual vs. Predicted IMDB Ratings", 
     sub = "Black = Actual, Blue = Predicted, Green = Actual Average, Red = Model Resids, Gold = Predicted - Avg")
abline(0,0)

# Plot Actual Rating average in Green4
test_avg = rep(mean(test$IMDBrating), length(test$IMDBrating))
lines(test_avg, type = "l", col = "green4", lwd = 2)

# Plot fitted values in blue
lines(pred_rf, type = "l", col = "blue", lwd = 3)

# Plot residuals in red as bars
lines(test$IMDBrating - pred_rf, type = "h", col = "red", lwd = 3)

# Plot Predicted - Average as gold dots
lines(pred_rf - test_avg, type = "p", col = "gold3")

##### Plot Random Forest
plot(rf1, main = "Random Forest Elbow Plot")

source("rf_plot.R")
tree_func(rf1, 2)

```



```{r}
# ML 3: Random Forest, using tree library
install.packages("tree")
library(tree)

rf2 <- tree(IMDBrating ~ ., data = train)
rf2

tree:::plot.rf2
```